server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/svproject?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        min-idle: 0

swagger:
  enabled: true

logging:
   level:
     com.yong.login.mapper: debug
jwt:
  tokenHeader: Authorization
  secret: springboot-vue
  expiration: 604800
  tokenHead: Bearer
